name: OpenJDK 11 S2I Image CI
on: [push, pull_request]
env:
  LANG: en_US.UTF-8
  CEKIT_VERSION: 3.6.0
  S2I_URI: https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz
jobs:
  openjdkci:
    name: OpenJDK S2I Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Verify latest UBI image is present
        run: |
          docker pull registry.access.redhat.com/ubi8/ubi-minimal:latest
          docker tag  registry.access.redhat.com/ubi8/ubi-minimal:latest registry.redhat.io/ubi8/ubi-minimal:latest
          docker image ls | grep ubi8
      - name: Setup required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y krb5-multidev virtualenv
      - name: Setup virtualenv and install cekit and required packages
        run: |
          mkdir ~/cekit${{ env.CEKIT_VERSION }}
          virtualenv ~/cekit${{ env.CEKIT_VERSION }}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pip install cekit==${{ env.CEKIT_VERSION }} docker docker-squash odcs behave lxml
      - name: Build
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          cekit -v --descriptor ubi8-openjdk-11.yaml build docker
          docker image ls
      - name: install s2i binary
        run: |
          echo ===== Installing s2i from ${{ env.S2I_URL }} =====
          mkdir /tmp/s2i/ && cd /tmp/s2i/
          wget ${{ env.S2I_URI }}
          tar xvf source-to-image*.gz
          sudo mv s2i /usr/bin
          which s2i
          s2i version
      - name: Behave Tests
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          cekit -v --descriptor ubi8-openjdk-11.yaml test behave
